language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      libicu-dev

r_github_packages: jimhester/covr

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.4
  - r: 3.3
  - r: 3.2